### ISSUE TITLE
Some advices to improve your project

### ISSUE THREAD

**Issue by vojtechmares** [KaminekLP/fileUP#2]
Hi, sice I see you are learning PHP, dont take this as hate - take it as an advice!

- Using pure PHP nowadays is very outdated. (Use [composer](https://getcomposer.org) instead - autoloading of classes and it gives you ability to use packages from [packagist](https://packagist.org) - USEFUL AF!
 - Use database to store data about the files which get uploaded - it allows you to easily maintain cron jobs such as automated file deleting (e.g. older than XX days).
- Add array of blacklisted file extensions (e.g. .php !!!)
- Do NOT give files the 777 rights - you allow other people code to be executed on your machine - SECURITY ISSUE - your machine will get hack in neck of time...
- Store most of the settings in database, the database connection settings, store them in .ini, .yaml or .json file format - PHP has built-in support for this file formats so you can easily parse them, recommandation: use caching for the config files - so you dont need to read them with every request
- Add more UI to the site - progress bar (jQuery can do it quite easy, or pure JS too (bit advanced)).
- Maybe some login system to maintain files uploaded by myself + admin system for deleting illegal stuff, e.g. distributing movies is illegal!

**That is the general stuff I can think of right now, feel free to send me a message if you want some help or just a talk. Contact me here on GitHub or on Hicoria forum [Aca](https://forum.hicoria.com/index.php?members/aca.2272/)**

**Comment by php-web-systems-constructions** [comment]
Hello,

all things, you are writed (progress bar, login, db etc.) is in progress. About 777 CHMODS, i fix that in next version. About security issue (blacklist), in next version i add that. Anyway, thank you. Closed
